### ISSUE TITLE
Firefox compatibility

### ISSUE THREAD

**Issue by yuchi328** [vinothpandian/react-sketch-canvas#54]
**Describe the bug**
Thanks for the new version release! I had an issue when using it on Firefox. It seems that the current version is not very compatible with Firefox, brush strokes are not displayed properly. 

**To Reproduce**
Run on Firefox browser, and draw.

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Firefox

**Comment by jsalgado2510** [comment]
I am having the same issue on Firefox with Fedora Linux. This issue doesn't occur with Google Chrome.

**Comment by vinothpandian** [comment]
Looks like a performance issue due to rendering. I wanted to change the underlying data structure of CanvasPath to handle this in v7.

If anyone else figures out a simpler way of solving this, please make a PR

**Comment by ivan-at-hypothetic** [comment]
Do you plan to work on this issue in the near future?

**Comment by vinothpandian** [comment]
@ivan-at-hypothetic Yes in the near future, but I didn't have much time to spend on it recently. However, if you have a fix, please send a PR.

**Comment by scomisario-osana** [comment]
Hi everyone!
Any news about this issue?

**Comment by vinothpandian** [comment]
Fixed with [7.0.0.next.0](https://www.npmjs.com/package/react-sketch-canvas/v/7.0.0-next.0) release

**Comment by zeke** [comment]
Hey @vinothpandian. Unfortunately I think this bug still persists in the new version you mentioned.

Here's a repro video: https://www.loom.com/share/b804e56441d6494f96d24e83dd2634ed

**Comment by zeke** [comment]
Here's how we're working around it: https://github.com/replicate/scribble-diffusion/issues/31#issuecomment-1451288647

**Comment by vinothpandian** [comment]
Thanks @zeke! Seems like the eraser is the problem. I will add a stroke eraser option where users can delete strokes as well.
